/*
 * DialogoES.java
 *
 * Created on 28 de diciembre de 2006, 0:57
 */

package ensamblador.vista;

import java.util.Vector;

import ensamblador.datos.Lenguaje;
import ensamblador.datos.Palabra;

/**
 *
 * @author  rake
 */
public class PanelES extends javax.swing.JPanel {
    Lenguaje lenguaje;
	
    /** Creates new form DialogoES */
    public PanelES() {
    	super();
    	lenguaje = Lenguaje.getInstancia();
        initComponents();
//        this.addKeyListener(new KeyAdapter() {
// 	 	  	public void keyPressed(KeyEvent evt){
// 	 			teclaPulsada(evt);
// 	 	  	}
//
// });
    }
//    private void teclaPulsada(KeyEvent evt){
//    	this.parent.teclaPulsada(evt);
//    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        JPanel1ES = new javax.swing.JPanel();
        jPanel2ES = new javax.swing.JPanel();
        labelReceiverControl = new javax.swing.JLabel();
        labelReceiverData = new javax.swing.JLabel();
        receiverControl = new javax.swing.JLabel();
        receiverData = new javax.swing.JLabel();
        jPanel3ES = new javax.swing.JPanel();
        labelTransmitterControl = new javax.swing.JLabel();
        labelTransmitterData = new javax.swing.JLabel();
        transmitterControl = new javax.swing.JLabel();
        transmitterData = new javax.swing.JLabel();

        this.setLayout(new java.awt.GridLayout());                
        JPanel1ES.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2ES.setBorder(javax.swing.BorderFactory.createTitledBorder(null, lenguaje.getString("teclado"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2ES.setAutoscrolls(true);
        labelReceiverControl.setText(lenguaje.getString("receiverControl")+"[0xffff0000]=");

        labelReceiverData.setText(lenguaje.getString("receiverData")+"    [0xffff0004]=");

        receiverControl.setText("0x00000000");

        receiverData.setText("0x00000000");

//        org.jdesktop.layout.GroupLayout jPanel2ESLayout = new org.jdesktop.layout.GroupLayout(jPanel2ES);
//        jPanel2ES.setLayout(jPanel2ESLayout);
//        jPanel2ESLayout.setHorizontalGroup(
//            jPanel2ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jPanel2ESLayout.createSequentialGroup()
//                .addContainerGap()
//                .add(jPanel2ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
//                    .add(org.jdesktop.layout.GroupLayout.LEADING, labelReceiverData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .add(org.jdesktop.layout.GroupLayout.LEADING, labelReceiverControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .add(28, 28, 28)
//                .add(jPanel2ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                    .add(receiverControl)
//                    .add(receiverData))
//                .addContainerGap(43, Short.MAX_VALUE))
//        );
//        jPanel2ESLayout.setVerticalGroup(
//            jPanel2ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jPanel2ESLayout.createSequentialGroup()
//                .addContainerGap()
//                .add(jPanel2ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(labelReceiverControl)
//                    .add(receiverControl))
//                .add(20, 20, 20)
//                .add(jPanel2ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(labelReceiverData)
//                    .add(receiverData))
//                .addContainerGap(16, Short.MAX_VALUE))
//        );
//        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2ES);
//        jPanel2ES.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jPanel2Layout.createSequentialGroup()
//                .addContainerGap()
//                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(labelReceiverControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
//                    .add(labelReceiverData))
////                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
////                    .add(org.jdesktop.layout.GroupLayout.LEADING, labelReceiverData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
////                    .add(org.jdesktop.layout.GroupLayout.LEADING, labelReceiverControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(receiverControl)
//                    .add(receiverData))
//                .addContainerGap(65, Short.MAX_VALUE))
//        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2ES);
        jPanel2ES.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelReceiverData)
                    .add(labelReceiverControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(receiverControl)
                    .add(receiverData))
                .add(78, 78, 78))
        );
        
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelReceiverControl)
                    .add(receiverControl))
                .add(20, 20, 20)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelReceiverData)
                    .add(receiverData))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        
        
        JPanel1ES.add(jPanel2ES);

        jPanel3ES.setBorder(javax.swing.BorderFactory.createTitledBorder(null, lenguaje.getString("monitor"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        labelTransmitterControl.setText(lenguaje.getString("transmitterControl")+"[0xffff0008]=");

        labelTransmitterData.setText(lenguaje.getString("transmitterData")+"    [0xffff000c]=");

        transmitterControl.setText("0x00000001");

        transmitterData.setText("0x00000000");

//        org.jdesktop.layout.GroupLayout jPanel3ESLayout = new org.jdesktop.layout.GroupLayout(jPanel3ES);
//        jPanel3ES.setLayout(jPanel3ESLayout);
//        jPanel3ESLayout.setHorizontalGroup(
//            jPanel3ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jPanel3ESLayout.createSequentialGroup()
//                .addContainerGap()
//                .add(jPanel3ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(labelTransmitterControl)
//                    .add(labelTransmitterData))
//                .add(25, 25, 25)
//                .add(jPanel3ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(transmitterData)
//                    .add(transmitterControl))
//                .addContainerGap(40, Short.MAX_VALUE))
//        );
//        jPanel3ESLayout.setVerticalGroup(
//            jPanel3ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jPanel3ESLayout.createSequentialGroup()
//                .addContainerGap()
//                .add(jPanel3ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(labelTransmitterControl)
//                    .add(transmitterControl))
//                .add(23, 23, 23)
//                .add(jPanel3ESLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(labelTransmitterData)
//                    .add(transmitterData))
//                .addContainerGap(13, Short.MAX_VALUE))
//        );

//        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3ES);
//        jPanel3ES.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jPanel3Layout.createSequentialGroup()
//                .addContainerGap()
//                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(labelTransmitterControl)
//                    .add(labelTransmitterData))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(transmitterControl)
//                    .add(transmitterData))
//                .addContainerGap(59, Short.MAX_VALUE))
//        );
        
        
        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3ES);
        jPanel3ES.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelTransmitterControl)
                    .add(labelTransmitterData))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(transmitterData)
                    .add(transmitterControl))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        
        
        
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelTransmitterControl)
                    .add(transmitterControl))
                .add(23, 23, 23)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelTransmitterData)
                    .add(transmitterData))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        
        JPanel1ES.add(jPanel3ES);

        this.add(JPanel1ES);
        
    }// </editor-fold>//GEN-END:initComponents
    
    public void actualizarValores(Vector<Palabra> valores){
    	/*Este vector tiene los cuatro valores correspondientes a la ES
    	 * y viene ordenados segun su direcc de mem de menor a mayor,i e,
    	 * de receiver control -->transmitter data*/
    	if(valores.size()==4){
    		this.receiverControl.setText(valores.elementAt(0).getHex());
    		this.receiverData.setText(valores.elementAt(1).getHex());
    		this.transmitterControl.setText(valores.elementAt(2).getHex());
    		if(!valores.elementAt(3).getHex().equals("0x00000000")){
//    			this.transmitterData.setText(new Palabra(valores.elementAt(3).getAscii(),true).getHex());
    			this.transmitterData.setText(valores.elementAt(3).getHex());
    		}
    	}else{
    		//imposible -->error
    	}
    	
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1ES;
    private javax.swing.JPanel jPanel2ES;
    private javax.swing.JPanel jPanel3ES;
    private javax.swing.JLabel labelReceiverControl;
    private javax.swing.JLabel labelReceiverData;
    private javax.swing.JLabel labelTransmitterControl;
    private javax.swing.JLabel labelTransmitterData;
    private javax.swing.JLabel receiverControl;
    private javax.swing.JLabel receiverData;
    private javax.swing.JLabel transmitterControl;
    private javax.swing.JLabel transmitterData;
    // End of variables declaration//GEN-END:variables
    
}
