/*
 * DialogoSegmentado.java
 *
 * Created on 19 de diciembre de 2006, 15:36
 */

package ensamblador;

import java.util.Vector;
import ensamblador.datos.Tipos;
import ensamblador.datos.Lenguaje;

/**
 *
 * @author  sonia
 */
public class DialogoSegmentado extends javax.swing.JDialog {

	private Ensamblador ensamblador;
	Lenguaje lenguaje;
	
    /** Creates new form DialogoSegmentado */
    public DialogoSegmentado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ensamblador=(Ensamblador)parent;
        lenguaje = Lenguaje.getInstancia();
        this.ensamblador.setVisible(true);
        initComponents();
        this.setSize(510, 300);
        this.setVisible(true);
        setValoresFus(ensamblador);
        setValoresTipoFus(ensamblador);       
    }
    
    private void setValoresFus(Ensamblador ensamblador) {
    	Vector<Vector> fus=new Vector<Vector>();
    	Vector<Integer> add=new Vector<Integer>();
    	Vector<Integer> mult=new Vector<Integer>();
    	Vector<Integer> div=new Vector<Integer>();

    	add.addElement(new Integer(comboAddFP.getSelectedItem().toString()));
    	add.addElement(new Integer(comboLatAdd.getSelectedItem().toString()));
    	mult.addElement(new Integer(comboMultFP.getSelectedItem().toString()));
    	mult.addElement(new Integer(comboLatMult.getSelectedItem().toString()));
    	div.addElement(new Integer(comboDivFP.getSelectedItem().toString()));
    	div.addElement(new Integer(comboLatDiv.getSelectedItem().toString()));

    	fus.addElement(add);
    	fus.addElement(mult);
    	fus.addElement(div);
    	ensamblador.setFus(fus);
    }
    
    private void setValoresTipoFus(Ensamblador ensamblador) {
    	Vector<Integer> tiposFus = new Vector<Integer>();

    	if(rbAddSegm.isSelected()) 
    		tiposFus.add(Tipos.UF_SEGM);    	
    	else 
    		tiposFus.add(Tipos.UF_NO_SEGM);
    	if(rbMultSegm.isSelected()) 
    		tiposFus.add(Tipos.UF_SEGM);    	
    	else 
    		tiposFus.add(Tipos.UF_NO_SEGM);
    	if(rbDivSegm.isSelected()) 
    		tiposFus.add(Tipos.UF_SEGM);    	
    	else 
    		tiposFus.add(Tipos.UF_NO_SEGM);
    	ensamblador.setTiposFus(tiposFus);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        grupoBotones1 = new javax.swing.ButtonGroup();
        grupoBotones2 = new javax.swing.ButtonGroup();
        grupoBotones3 = new javax.swing.ButtonGroup();
        grupoBotones4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUnidades = new javax.swing.JLabel();
        labelLatencia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelInt = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboInt = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboLatInt = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        labelAddFP = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        rbAddSegm = new javax.swing.JRadioButton();
        rbAddNoSegm = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        comboAddFP = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        comboLatAdd = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        labelMultFP = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        rbMultSegm = new javax.swing.JRadioButton();
        rbMultNoSegm = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        comboMultFP = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        comboLatMult = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        labelDivFP = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        rbDivSegm = new javax.swing.JRadioButton();
        rbDivNoSegm = new javax.swing.JRadioButton();
        jLabel65 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        comboDivFP = new javax.swing.JComboBox();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        comboLatDiv = new javax.swing.JComboBox();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonAceptar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        
        
        setTitle(lenguaje.getString("UNIDADES_FUNCIONALES"));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        
        
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.add(jPanel13);

        jPanel12.setLayout(new java.awt.GridLayout(1, 4));

        jPanel12.add(jLabel1);

        jPanel12.add(jLabel2);

        labelUnidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUnidades.setText(lenguaje.getString("unidades"));
        labelUnidades.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel12.add(labelUnidades);

        labelLatencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLatencia.setText(lenguaje.getString("latencia"));
        jPanel12.add(labelLatencia);

        jPanel1.add(jPanel12);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        jPanel8.setLayout(new java.awt.BorderLayout());

        labelInt.setFont(new java.awt.Font("Dialog", 1, 11));
        labelInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInt.setText("Int    ");
        jPanel8.add(labelInt, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(4, 1));

        jPanel9.add(jLabel23);

        jPanel9.add(jLabel24);

        jPanel9.add(jLabel3);

        jPanel9.add(jLabel4);

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(3, 3));

        jPanel10.add(jLabel7);

        jPanel10.add(jLabel8);

        jPanel10.add(jLabel9);

        jPanel10.add(jLabel10);

        comboInt.setEnabled(false);
        jPanel10.add(comboInt);

        jPanel10.add(jLabel11);

        jPanel10.add(jLabel12);

        jPanel10.add(jLabel13);

        jPanel10.add(jLabel14);

        jPanel4.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(3, 3));

        jPanel11.add(jLabel15);

        jPanel11.add(jLabel16);

        jPanel11.add(jLabel17);

        jPanel11.add(jLabel18);

        comboLatInt.setEnabled(false);
        
        jPanel11.add(comboLatInt);

        jPanel11.add(jLabel19);

        jPanel11.add(jLabel20);

        jPanel11.add(jLabel21);

        jPanel11.add(jLabel22);

        jPanel4.add(jPanel11);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        jPanel14.setLayout(new java.awt.BorderLayout());

        labelAddFP.setFont(new java.awt.Font("Dialog", 1, 11));
        labelAddFP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddFP.setText("Add FP");
        jPanel14.add(labelAddFP, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(4, 1));

        jPanel15.add(jLabel26);

        rbAddSegm.setFont(new java.awt.Font("Dialog", 1, 10));
        rbAddSegm.setSelected(true);
        rbAddSegm.setText(lenguaje.getString("segmentadas"));
        rbAddSegm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAddSegmActionPerformed(evt);
            }
        });

        grupoBotones2.add(rbAddSegm);
        jPanel15.add(rbAddSegm);

        rbAddNoSegm.setFont(new java.awt.Font("Dialog", 1, 10));
        rbAddNoSegm.setText(lenguaje.getString("noSegmentadas"));
        rbAddNoSegm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAddNoSegmActionPerformed(evt);
            }
        });
        grupoBotones2.add(rbAddNoSegm);
        jPanel15.add(rbAddNoSegm);

        jPanel15.add(jLabel27);

        jPanel5.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(3, 3));

        jPanel16.add(jLabel28);

        jPanel16.add(jLabel29);

        jPanel16.add(jLabel30);

        jPanel16.add(jLabel31);

        comboAddFP.setEnabled(false);
        jPanel16.add(comboAddFP);

        jPanel16.add(jLabel32);

        jPanel16.add(jLabel33);

        jPanel16.add(jLabel34);

        jPanel16.add(jLabel35);

        jPanel5.add(jPanel16);

        jPanel17.setLayout(new java.awt.GridLayout(3, 3));

        jPanel17.add(jLabel36);

        jPanel17.add(jLabel37);

        jPanel17.add(jLabel38);

        jPanel17.add(jLabel39);

        jPanel17.add(comboLatAdd);

        jPanel17.add(jLabel40);

        jPanel17.add(jLabel41);

        jPanel17.add(jLabel42);

        jPanel17.add(jLabel43);

        jPanel5.add(jPanel17);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 4));

        jPanel18.setLayout(new java.awt.BorderLayout());

        labelMultFP.setFont(new java.awt.Font("Dialog", 1, 11));
        labelMultFP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMultFP.setText("Mult FP");
        jPanel18.add(labelMultFP, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(4, 1));

        jPanel19.add(jLabel45);

        rbMultSegm.setFont(new java.awt.Font("Dialog", 1, 10));
        rbMultSegm.setSelected(true);
        rbMultSegm.setText(lenguaje.getString("segmentadas"));
        rbMultSegm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMultSegmActionPerformed(evt);
            }
        });
        grupoBotones3.add(rbMultSegm);
        jPanel19.add(rbMultSegm);

        rbMultNoSegm.setFont(new java.awt.Font("Dialog", 1, 10));
        rbMultNoSegm.setText(lenguaje.getString("noSegmentadas"));
        rbMultNoSegm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMultNoSegmActionPerformed(evt);
            }
        });
        grupoBotones3.add(rbMultNoSegm);
        jPanel19.add(rbMultNoSegm);

        jPanel19.add(jLabel46);

        jPanel6.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(3, 3));

        jPanel20.add(jLabel47);

        jPanel20.add(jLabel48);

        jPanel20.add(jLabel49);

        jPanel20.add(jLabel50);

        comboMultFP.setEnabled(false);
        jPanel20.add(comboMultFP);

        jPanel20.add(jLabel51);

        jPanel20.add(jLabel52);

        jPanel20.add(jLabel53);

        jPanel20.add(jLabel54);

        jPanel6.add(jPanel20);

        jPanel21.setLayout(new java.awt.GridLayout(3, 3));

        jPanel21.add(jLabel55);

        jPanel21.add(jLabel56);

        jPanel21.add(jLabel57);

        jPanel21.add(jLabel58);

        jPanel21.add(comboLatMult);

        jPanel21.add(jLabel59);

        jPanel21.add(jLabel60);

        jPanel21.add(jLabel61);

        jPanel21.add(jLabel62);

        jPanel6.add(jPanel21);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 4));

        jPanel22.setLayout(new java.awt.BorderLayout());

        labelDivFP.setFont(new java.awt.Font("Dialog", 1, 11));
        labelDivFP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDivFP.setText("Div FP");
        jPanel22.add(labelDivFP, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel22);

        jPanel23.setLayout(new java.awt.GridLayout(4, 1));

        jPanel23.add(jLabel64);

        rbDivSegm.setFont(new java.awt.Font("Dialog", 1, 10));
        //rbDivSegm.setSelected(true);
        rbDivSegm.setText(lenguaje.getString("segmentadas"));
        rbDivSegm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDivSegmActionPerformed(evt);
            }
        });
        grupoBotones4.add(rbDivSegm);
        jPanel23.add(rbDivSegm);

        rbDivNoSegm.setFont(new java.awt.Font("Dialog", 1, 10));
        rbDivNoSegm.setSelected(true);
        rbDivNoSegm.setText(lenguaje.getString("noSegmentadas"));
        rbDivNoSegm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDivNoSegmActionPerformed(evt);
            }
        });
        grupoBotones4.add(rbDivNoSegm);
        jPanel23.add(rbDivNoSegm);

        jPanel23.add(jLabel65);

        jPanel7.add(jPanel23);

        jPanel24.setLayout(new java.awt.GridLayout(3, 3));

        jPanel24.add(jLabel66);

        jPanel24.add(jLabel67);

        jPanel24.add(jLabel68);

        jPanel24.add(jLabel69);

        comboDivFP.setEnabled(true);
        jPanel24.add(comboDivFP);

        jPanel24.add(jLabel70);

        jPanel24.add(jLabel71);

        jPanel24.add(jLabel72);

        jPanel24.add(jLabel73);

        jPanel7.add(jPanel24);

        jPanel25.setLayout(new java.awt.GridLayout(3, 3));

        jPanel25.add(jLabel74);

        jPanel25.add(jLabel75);

        jPanel25.add(jLabel76);

        jPanel25.add(jLabel77);

        jPanel25.add(comboLatDiv);

        jPanel25.add(jLabel78);

        jPanel25.add(jLabel79);

        jPanel25.add(jLabel80);

        jPanel25.add(jLabel81);

        jPanel7.add(jPanel25);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        
        comboInt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1"}));       
        comboAddFP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));        
        comboMultFP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        comboDivFP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        comboLatInt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1"}));
        comboLatAdd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));        
        comboLatMult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        comboLatDiv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        Vector<Vector> fus = ensamblador.getFus();
        if (fus.size() >= 3) {
          /* si ya se han seleccionado latencias anteriormente, mantener esos valores */
          comboLatAdd.setSelectedIndex(((Vector<Integer>)fus.elementAt(0)).elementAt(1) - 1);
          comboLatMult.setSelectedIndex(((Vector<Integer>)fus.elementAt(1)).elementAt(1) - 1);
          comboLatDiv.setSelectedIndex(((Vector<Integer>)fus.elementAt(2)).elementAt(1) - 1);
        } else {
          /* si no, utilizar latencias por defecto: (2, 4, 7) */
          comboLatAdd.setSelectedIndex(1);
          comboLatMult.setSelectedIndex(3);
          comboLatDiv.setSelectedIndex(6);
        }
        
        buttonAceptar.setText(lenguaje.getString("aceptar"));
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });
        jPanel3.add(buttonAceptar);

        buttonCancelar.setText(lenguaje.getString("cancelar"));
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCancelar);

        
        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    

    
    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {
    	this.setValoresFus(ensamblador);
    	this.setValoresTipoFus(ensamblador);
    	this.setVisible(false);
    	this.setEnabled(false);    	
     	this.dispose();     	    	
    }
    
    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {    	
    	this.setVisible(false);
    	this.setEnabled(false);
    	this.dispose();
    	
    }
    
    private void rbAddSegmActionPerformed(java.awt.event.ActionEvent evt) {
    	comboAddFP.setSelectedIndex(0);
    	comboAddFP.setEnabled(false);
    }
    
    private void rbAddNoSegmActionPerformed(java.awt.event.ActionEvent evt) {
    	comboAddFP.setEnabled(true);
    }
    
    private void rbMultSegmActionPerformed(java.awt.event.ActionEvent evt) {
    	comboMultFP.setSelectedIndex(0);
    	comboMultFP.setEnabled(false);
    }
    
    private void rbMultNoSegmActionPerformed(java.awt.event.ActionEvent evt) {
    	comboMultFP.setEnabled(true);
    }
    
    private void rbDivSegmActionPerformed(java.awt.event.ActionEvent evt) {
    	comboDivFP.setSelectedIndex(0);
    	comboDivFP.setEnabled(false);
    }
    
    private void rbDivNoSegmActionPerformed(java.awt.event.ActionEvent evt) {
    	comboDivFP.setEnabled(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JComboBox comboAddFP;
    private javax.swing.JComboBox comboDivFP;
    private javax.swing.JComboBox comboInt;
    private javax.swing.JComboBox comboLatAdd;
    private javax.swing.JComboBox comboLatDiv;
    private javax.swing.JComboBox comboLatInt;
    private javax.swing.JComboBox comboLatMult;
    private javax.swing.JComboBox comboMultFP;
    private javax.swing.ButtonGroup grupoBotones1;
    private javax.swing.ButtonGroup grupoBotones2;
    private javax.swing.ButtonGroup grupoBotones3;
    private javax.swing.ButtonGroup grupoBotones4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelAddFP;
    private javax.swing.JLabel labelDivFP;
    private javax.swing.JLabel labelInt;
    private javax.swing.JLabel labelLatencia;
    private javax.swing.JLabel labelMultFP;
    private javax.swing.JLabel labelUnidades;
    private javax.swing.JRadioButton rbAddNoSegm;
    private javax.swing.JRadioButton rbAddSegm;
    private javax.swing.JRadioButton rbDivNoSegm;
    private javax.swing.JRadioButton rbDivSegm;
    private javax.swing.JRadioButton rbMultNoSegm;
    private javax.swing.JRadioButton rbMultSegm;
    // End of variables declaration//GEN-END:variables
    
}
